# Site settings
baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Lagoon"
theme = "syna"
enableGitInfo = true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
ignorefiles = [ "content/dev/.*" ]

# Google Analytics tracking
googleAnalytics = "G-QN0G2JGKSP"

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
  date = ["date", "lastmod"]
  lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  name = "the Lagoon authors"
  description = "Open source WebOps platform"
  debug = true
  unsafeEvents = true # Default is false. Enables ?event=type format of url events.

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"

  # Piwik tracking
  [params.analytics.piwik]
    #url = "https://use.example.net"
    #id = ""
    #domain = "*" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#4578E6"
    secondary = "#32C8B4"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    ltgrey= "#c3c3c3"
    dkgrey = "#7e7e7e"
    light = "#f8f9fa"
    dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# footer/footer_social menus are displayed in footer fragment.
# copyright_footer menus are displayed in copyright fragment
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  url = "/features"
  name = "Features"
  weight = 20

[[menu.main]]
  url = "https://docs.lagoon.sh"
  name = "Docs"
  weight = 30

[[menu.main]]
  url = "https://github.com/uselagoon/lagoon#lagoon---the-developer-focused-application-delivery-platform-for-kubernetes"
  name = "About"
  weight = 40

[[menu.main]]
  url = "https://dev.to/uselagoon"
  name = "Blog"
  weight = 50

[[menu.footer]]
  url = "https://docs.lagoon.sh"
  name = "Getting Started"
  weight = 10

[[menu.footer]]
  url = "https://www.amazee.io/"
  name = "About amazee.io"
  weight = 20

[[menu.copyright_footer]]
  url = "https://lagoon.sh"
  name = "Proudly hosted on Lagoon"
  weight = 10
